---
- name: Destroy google cloud instances
  hosts: localhost
  become: true
  vars_files:
    - ../../vars/machines.yaml
  tasks:
    - name: Destroy GCP instances
      include_tasks: tasks/destroy-gcp-instance.yaml
      loop: "{{ machines_info }}"
      loop_control:
        loop_var: machine
