---
- name: Create Google Cloud Instance 
  hosts: localhost 
  become: true
  vars: 
    machine_name: master1
    google_project_id: driven-tenure-462201-k3
    # location where you put the service account.json file 
    service_account_path: ../service-account.json
    ssh_public_key_path: /home/tochratana/.ssh/id_rsa.pub
  tasks:
    - name: create first gcp instance 
      import_tasks: tasks/create-gcp-task.yaml
# ansible-playbook playbooks/create-gcp-instance.yaml